gemfile: Gemfile


PreCommit:

  ALL:
    on_warn: fail

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    command: ["bundle", "exec", "rubocop"]

  YamlSyntax:
    enabled: true

  CustomScript:
    enabled: true
    description: "Verify specs all pass"
    command: ["make", "verify-specs"]

  LineEndings:
    enabled: true

  TrailingWhitespace:
    enabled: true


CommitMsg:

  TextWidth:
    enabled: true
    max_subject_width: 72
    min_subject_width: 10
    max_body_width: 80

  HardTabs:
    enabled: true

  RussianNovel:
    enabled: true


PrePush:

  ProtectedBranches:
    enabled: true
