---


# Provide more details in output.
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

# We don't need/want Rails for this project.
Rails:
  Enabled: false

# Allow longer lines.
Metrics/LineLength:
  Max: 160

# Don't require documentation for everything.
Style/Documentation:
  Enabled: false

# Outdent `private`/`protected`/`public`. NOTE: Also includes `module_function` (but I don't think that should be outdented).
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# Use `{}` for blocks that return a value; otherwise use `do` and `end`.
# We make a few exceptions, mostly for RSpec.
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - expect
  IgnoredMethods:
    - rule
    - rule!
    - let
    - let!
    - subject

# Don't require `freeze` on every immutable constant.
Style/MutableConstant:
  Enabled: false

# I don't want to add `# frozen_string_literal: true` to every file in Ruby 2.3+.
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't use backticks -- they're too hard to distinguish.
Style/CommandLiteral:
  EnforcedStyle: percent_x

# Don't require underscores for long numeric literals.
Style/NumericLiterals:
  Enabled: false

# Require blank lines inside class/module definitions.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

# Allow (but don't require) extra empty lines.
Layout/EmptyLines:
  Enabled: false

# Don't require empty methods to have the `def` and `end` on a single line.
Style/EmptyMethod:
  Enabled: false

# Use `[]` for `%w`, to remind us that we're creating an Array.
# Use `[]` for `%x`, because it looks kind of like an input box.
# Use `{}` for `%q`, because it's set off a bit nicer than `()`.
# Use `{}` for `%r`, because regular expressions might have unbalanced `()` or `<>`.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': []
    '%W': []
    '%x': []
    '%': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'

# Allow explicit `self`, as it adds clarity on occasion.
Style/RedundantSelf:
  Enabled: false

# Use `%r` for regular expressions that span more than 1 line.
Style/RegexpLiteral:
  EnforcedStyle: mixed

# Use Jim Weirich's suggestion of using `fail`, except when re-raising an exception.
Style/SignalException:
  EnforcedStyle: semantic

# Default to double quotes, as they require less incidental changes.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Allow either type of quotes within the Ruby code inside interpolations.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Allow (but don't require) a space before a block brace.
Layout/SpaceBeforeBlockBraces:
  Enabled: false

# Don't allow a space directly inside a Hash literal.
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Require a space directly inside a block delineated with braces.
# This is the default, but I wanted to call it out in contrast to Hash literals.
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

# When using multi-line Arrays and Hashes, ensure the first element is also on its own line.
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true

# Allow (but don't require) trailing comma in Array and Hash literals.
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# Don't complain about the block comments generated by RSpec.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Allow `send`. (It might be better to prefer `__send__` or `public_send`, but I'm not 100% convinced.)
Style/Send:
  Enabled: false

# Don't complain that `has_many` doesn't end with a question mark.
Naming/PredicateName:
  NameWhitelist:
    - has_many

# Allow `has_key?` and `has_value?` on Hash, as they read better than `key?` and `value?`.
Style/PreferredHashMethods:
  Enabled: false

# Ensure there's a newline at the end of the file, but not a blank line.
Layout/TrailingBlankLines:
  EnforcedStyle: final_newline

# Allow assigning to the same variable in multiple branches of an `if` or `case`.
Style/ConditionalAssignment:
  Enabled: false

# Allow long blocks in specs and tests.
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - test/**/*

# Don't require use of Ruby 2.3+ safe navigation operator.
Style/SafeNavigation:
  Enabled: false

# Allow `!!` to force a boolean result.
Style/DoubleNegation:
  Enabled: false

# Allow non-ASCII identifiers.
Naming/AsciiIdentifiers:
  Enabled: false


## Exceptions.

# Some of our classes are going to be long.
Metrics/ClassLength:
  Max: 250

# Not sure why `∧` and `∨` are problematic, even after allowing non-ASCII identifiers.
# Also allow `builtin_ClassName` methods.
Naming/MethodName:
  Exclude:
  - src/extensions/boolean.rb
  - src/stone/top.rb

# I don't believe `module_function` should be outdented like `private`, but there's no way to turn it off for just `module_function`.
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  Exclude:
    - src/stone/top.rb

# Disabling this only because it's breaking RuboCop (at least 0.53 to 0.58.2).
Style/PercentLiteralDelimiters:
  Enabled: false
